# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('features', models.CharField(max_length=128, unique=True)),
                ('place', models.CharField(max_length=128, unique=True)),
                ('cost', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(max_length=128, unique=True)),
                ('welcomeComment', models.CharField(max_length=400, unique=True)),
                ('webLink', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=400, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artlink.Review'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artlink.Sense'),
        ),
    ]
